### ISSUE TITLE
65K methods over issue

### ISSUE THREAD

**Issue by ghost** [viniciusthiengo/nosso-chate#1]
How to overcome this?

**Comment by viniciusthiengo** [comment]
@vptcr whats up?!
So that mean your Android project are referencing at least 65k methods. It happens because you are probably using a lot of libraries. Try looking for some libraries that you can just take out of your project. If none is able to be out, then try put only the specific parts that your project needs, for example: google play services library can be referenced in a worst way, I meant, when you just need a couple of services you can keep using play services compile like this:

compile 'com.google.android.gms:play-services:8.4.0'

Go here: https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project
and try to fix that referencing just the play services libraries that you really need, of course if play services is part of your project and you are doing something like i'was showing before. And play services was just an example, you need to do that with all the libraries you are using in your project.

And in last situation try this: http://developer.android.com/intl/pt-br/tools/building/multidex.html
In that link they talk about that problem and how to solve it.

Have a good one
